import EventContext from '../Interfaces/EventContext'

function Event(
	type:
		| 'channelCreate'
		| 'channelDelete'
		| 'channelPinsUpdate'
		| 'channelUpdate'
		| 'clientUserGuildSettingsUpdate'
		| 'debug'
		| 'disconnect'
		| 'emojiCreate'
		| 'emojuUpdate'
		| 'emojiDelete'
		| 'error'
		| 'guildBanAdd'
		| 'guildBanRemove'
		| 'guildCreate'
		| 'guildDelete'
		| 'guildMemberAdd'
		| 'guildMemberAvailable'
		| 'guildMemberRemove'
		| 'guildMemberSpeaking'
		| 'guildMemberUpdate'
		| 'guildMembersChunk'
		| 'guildUnvailable'
		| 'guildUpdate'
		| 'message'
		| 'messageDelete'
		| 'messageDeleteBulk'
		| 'messageReactionAdd'
		| 'messageReactionRemove'
		| 'messageReactionRemoveAll'
		| 'messageUpdate'
		| 'presenceUpdate'
		| 'rateLimit'
		| 'raw'
		| 'ready'
		| 'reconnecting'
		| 'roleCreate'
		| 'roleDelete'
		| 'roleUpdate'
		| 'typingStart'
		| 'typingStop'
		| 'userNoteUpdate'
		| 'userUpdate'
		| 'voiceStateUpdate'
		| 'warn'
) {
	return function (constructor: Function) {
		constructor.prototype.name = type
	}
}

export { Event, EventContext }
